APIBankingASP.NET/Models/FundsTransferByCustomerService2.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace APIBankingASP.NET.Models
{
    namespace FundsTransferByCustomerService2
    {
        public class BeneficiaryAddress
        {
            public String address1 { get; set; }
            public String address2 { get; set; }
            public String address3 { get; set; }
            public String postalCode { get; set; }
            public String city { get; set; }
            public String stateOrProvince { get; set; }
            public String country { get; set; }
        }
            
        public class BeneficiaryContact
        {
            public String mobileNo { get; set; }
            public String emailID { get; set; }
        }

        public enum TransferType
        {
            FT,
            IMPS,
            NEFT,
            ANY,
            RTGS
        }

        public enum LastTransferStatus
        {
            IN_PROCESS,
            COMPLETED,
            FAILED,
            SENT_TO_BENEFICIARY,
            RETURNED_FROM_BENEFICIARY,
            SCHEDULED_FOR_NEXT_WORKDAY,
            ONHOLD
        }

     

        public class TransactionStatus
        {
            public LastTransferStatus statusCode;
            public String subStatusCode;
            public String bankReferenceNo;
            public String beneReferenceNo;
            public String reason;
        }

        public class TransferRequest : Credentials
        {
            [Required]
            public String uniqueRequestNo { get; set; }
            public String appID { get; set; }
            public String purposeCode { get; set; }
            public String customerID { get; set; }
            public String debitAccountNo { get; set; }
            public String beneficiaryCode { get; set; }

            public String beneficiaryName { get; set; }
            public BeneficiaryAddress beneficiaryAddress { get; set; }
            public BeneficiaryContact beneficiaryContact { get; set; }
            public String beneficiaryAccountNo { get; set; }
            public String beneficiaryIFSCCode { get; set; }
            public String beneficiaryMobileForMMID { get; set; }
            public String beneficiaryMMID { get; set; }

            public String transferCurrencyCode { get; }
            public TransferType transferType { get; set; }
            public Decimal transferAmount { get; set; }
            public String rmtrToBeneInfo { get; set; }

            public TransferRequest()
            {
                this.transferCurrencyCode = "INR";
                this.beneficiaryAddress = new BeneficiaryAddress();
                this.beneficiaryContact = new BeneficiaryContact();
            }
        }

        public class TransferResult
        {
            public String version;
            public String uniqueResponseNo;
            public Decimal attemptNo;
            public TransferType? transferType;
            public Boolean? lowBalanceAlert;
            public TransactionStatus transferStatus;
            public String nameWithBeneBank;
            public String requestReferenceNo;

            public TransferResult()
            {
                this.transferStatus = new TransactionStatus();
            }
        }

        public class GetBalanceRequest : Credentials
        {
            [Required]
            public String appID { get; set; }
            public String customerID { get; set; }
            public String AccountNumber { get; set; }

        }

        public class GetBalanceResult
        {
            [Required]
            public String version;
            public String accountCurrencyCode;
            public Decimal accountBalanceAmount;
            public Boolean? lowBalanceAlert;

        }

        public class GetStatusRequest : Credentials
        {
            [Required]
            public String appID { get; set; }
            public String customerID { get; set; }
            public String requestReferenceNo { get; set; }

        }

        public class GetStatusResult
        {
            [Required]
            public String version;
            public TransferType? transferType;
            public TransferType? reqTransferType;
            public DateTime transactionDate;
            public Decimal transferAmount;
            public String transferCurrencyCode;
            public TransactionStatus transferStatus;

            public GetStatusResult()
            {
                this.transferStatus = new TransactionStatus();
            }

        }
    }
}

APIBankingASP.NET/Models/GetBalance.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace APIBankingASP.NET.Models
{
    namespace DomesticRemittanceByPartnerService
    { 
        public class GetBalanceRequest : Credentials
        {
            public String version { get; set; }
            public String partnerCode { get; set; }
            public String customerID { get; set; }
            public String accountNo { get; set; } 
        }
        public class GetBalanceResult
        {
            public String version { get; set; }
            public String accountCurrencyCode { get; set; }
            public Decimal accountBalanceAmount { get; set; }
            public Boolean lowBalanceAlert { get; set; }
        }
    }
}

APIBankingASP.NET/Controllers/FundsTransferByCustomerService2Controller.cs
using APIBankingASP.NET.Helpers;
using APIBankingASP.NET.Models.FundsTransferByCustomerService2;
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.ServiceModel.Security;
using System.Web;
using System.Web.Mvc;

namespace APIBankingASP.NET.Controllers
{
    public class FundsTransferByCustomerService2Controller : Controller
    {

        private TransferRequest getTransferRequest(String appID, String customerID, String debitAccountNo, String purposeCode)
        {
            TransferRequest req = new TransferRequest();
            req.uniqueRequestNo = Guid.NewGuid().ToString().Replace("-", "");
            req.appID = appID;
            req.customerID = customerID;
            req.debitAccountNo = debitAccountNo;
            req.transferType = TransferType.NEFT;
            req.transferAmount = 100;
            req.rmtrToBeneInfo = "OnBoarding";
            req.purposeCode = purposeCode;
            return req;
        }

        public ActionResult getBalance()
        {
            GetBalanceRequest req = new GetBalanceRequest();

            req.appID = "299915";
            req.customerID = "299915";
            req.AccountNumber = "000380800000781";
            

            return View(req);
        }

        public ActionResult getStatus()
        {
            GetStatusRequest req = new GetStatusRequest();

            req.appID = "299915";
            req.customerID = "299915";
            req.requestReferenceNo = "012140";

            return View(req);
        }

        // GET: FundsTransferByCustomerService with beneficiary detail
        public ActionResult transferWithBeneDetail()
        {
            TransferRequest req;
            req = getTransferRequest("299915", "299915", "000380800000781", null);
            req.beneficiaryName = "Quantiguous Solutions";
            req.beneficiaryAddress.address1 = "Wilston Road";
            req.beneficiaryAddress.country = "IN";
            req.beneficiaryContact.emailID = "hello@quantiguous.com";
            req.beneficiaryContact.mobileNo = "9561234523";
            req.beneficiaryAccountNo = "026291800001191";
            req.beneficiaryIFSCCode = "HDFC0000001";
            req.beneficiaryMobileForMMID = "9869581569";
            req.beneficiaryMMID = "9532870";

            // transfer with bene detail view
            return View("transferWithBeneDetail", req);

        }

        // GET: FundsTransferByCustomerService with beneficiary code
        public ActionResult transferWithBeneCode()
        {
            TransferRequest req;
            req = getTransferRequest("26528", "26528", "000183200000030", "DOSI");
            req.beneficiaryCode = "ESECURE";

            // transfer with bene code
            return View("transferWithBeneCode", req);
        }


        [HttpPost]
        public ActionResult transfer(TransferRequest request)
        {
            if (TryValidateModel(request) == false)
            {
                return View(request);
            }

            APIBankingASP.NET.Models.Fault fault;

            APIBanking.Environment env = request.buildEnvironment();

            com.quantiguous.ft2.transfer apiReq = new com.quantiguous.ft2.transfer();
            com.quantiguous.ft2.transferResponse apiRep;

            apiReq.uniqueRequestNo = request.uniqueRequestNo;
            apiReq.purposeCode = request.purposeCode;
            apiReq.customerID = request.customerID;
            apiReq.debitAccountNo = request.debitAccountNo;

            //we have an optional element here, pass either beneficiary code or beneficiary detail
            if (request.beneficiaryCode == null)
            {
                com.quantiguous.ft2.beneficiaryType a = new com.quantiguous.ft2.beneficiaryType();
                a.Item = getBeneficiaryDetail(request);
                apiReq.beneficiary = a;
            }
            else
            {
                apiReq.beneficiary = getBeneficiaryCode(request.beneficiaryCode);
            }

            apiReq.transferType = getTransferType(request.transferType);
            apiReq.transferCurrencyCode = com.quantiguous.ft2.currencyCodeType.INR;
            apiReq.transferAmount = (float)request.transferAmount;
            apiReq.remitterToBeneficiaryInfo = request.rmtrToBeneInfo;


            try
            {
                apiRep = FundsTransferByCustomerClient.transfer(env, apiReq);

                TransferResult result = new TransferResult();

                result.version = apiRep.version;
                result.uniqueResponseNo = apiRep.uniqueResponseNo;
                result.attemptNo = int.Parse(apiRep.attemptNo);
                result.transferType = getTransferType(apiRep.transferType);
                result.lowBalanceAlert = apiRep.lowBalanceAlert;

                result.transferStatus.statusCode = getStatusCode(apiRep.transactionStatus.statusCode);
                result.transferStatus.subStatusCode = apiRep.transactionStatus.subStatusCode;
                result.transferStatus.bankReferenceNo = apiRep.transactionStatus.bankReferenceNo;
                result.requestReferenceNo = apiRep.requestReferenceNo;
                return View("transferResult", result);

            }
            /* 
             * the following exceptions have to be caught separately, even when you handle then the same way 
             * this is because of the way the APIBanking.Fault is created
             */
            catch (MessageSecurityException e)
            {
                fault = new APIBankingASP.NET.Models.Fault(new APIBanking.Fault(e));
            }
            catch (FaultException e)
            {
                fault = new APIBankingASP.NET.Models.Fault(new APIBanking.Fault(e));
            }
            catch (Exception e)
            {
                fault = new APIBankingASP.NET.Models.Fault(new APIBanking.Fault(e));
            }
            return View("fault", fault);

        }

        [HttpPost]
        public ActionResult getbalance(GetBalanceRequest request)
        {
            if (TryValidateModel(request) == false)
            {
                return View(request);
            }

            APIBankingASP.NET.Models.Fault fault;

            APIBanking.Environment env = request.buildEnvironment();

            com.quantiguous.ft2.getBalance apiReq = new com.quantiguous.ft2.getBalance();
            com.quantiguous.ft2.getBalanceResponse apiRep;

            apiReq.appID = request.appID;
            apiReq.customerID = request.customerID;
            apiReq.AccountNumber = request.AccountNumber;
            
            try
            {
                apiRep = FundsTransferByCustomerClient.getBalance(env, apiReq);

                GetBalanceResult result = new GetBalanceResult();

                result.version = apiRep.Version;
                result.accountCurrencyCode = apiRep.accountCurrencyCode.ToString();
                result.accountBalanceAmount = Convert.ToDecimal(apiRep.accountBalanceAmount);
                result.lowBalanceAlert = apiRep.lowBalanceAlert;
                return View("getBalanceResult", result);

            }
            /* 
             * the following exceptions have to be caught separately, even when you handle then the same way 
             * this is because of the way the APIBanking.Fault is created
             */
            catch (MessageSecurityException e)
            {
                fault = new APIBankingASP.NET.Models.Fault(new APIBanking.Fault(e));
            }
            catch (FaultException e)
            {
                fault = new APIBankingASP.NET.Models.Fault(new APIBanking.Fault(e));
            }
            catch (Exception e)
            {
                fault = new APIBankingASP.NET.Models.Fault(new APIBanking.Fault(e));
            }
            return View("fault", fault);

        }

        [HttpPost]
        public ActionResult getStatus(GetStatusRequest request)
        {
            if (TryValidateModel(request) == false)
            {
                return View(request);
            }

            APIBankingASP.NET.Models.Fault fault;

            APIBanking.Environment env = request.buildEnvironment();

            com.quantiguous.ft2.getStatus apiReq = new com.quantiguous.ft2.getStatus();
            com.quantiguous.ft2.getStatusResponse apiRep;

            apiReq.appID = request.appID;
            apiReq.customerID = request.customerID;
            apiReq.requestReferenceNo = request.requestReferenceNo;

            try
            {
                apiRep = FundsTransferByCustomerClient.getStatus(env, apiReq);

                GetStatusResult result = new GetStatusResult();

                result.version = apiRep.version;
                result.transferType = getTransferType(apiRep.transferType);
                result.reqTransferType = getTransferType(apiRep.reqTransferType);
                result.transactionDate = apiRep.transactionDate;
                result.transferAmount = Convert.ToDecimal(apiRep.transferAmount);
                result.transferCurrencyCode = apiRep.transferCurrencyCode.ToString();
                result.transferStatus.statusCode = getStatusCode(apiRep.transactionStatus.statusCode);
                result.transferStatus.bankReferenceNo = apiRep.transactionStatus.bankReferenceNo;
                result.transferStatus.beneReferenceNo = apiRep.transactionStatus.beneficiaryReferenceNo;
                result.transferStatus.reason = apiRep.transactionStatus.reason;
                return View("getStatusResult", result);

            }
            /* 
             * the following exceptions have to be caught separately, even when you handle then the same way 
             * this is because of the way the APIBanking.Fault is created
             */
            catch (MessageSecurityException e)
            {
                fault = new APIBankingASP.NET.Models.Fault(new APIBanking.Fault(e));
            }

APIBankingASP.NET/Views/FundsTransferByCustomerService2/getBalance.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@model APIBankingASP.NET.Models.FundsTransferByCustomerService2.GetBalanceRequest
@using (Html.BeginForm(new { @class = "form-horizontal" }))
{
    @Html.ValidationSummary(true)

    @Html.EditorFor(m => m);

    <fieldset>
        <legend>Request</legend>
        <div class="form-group">
            @Html.LabelFor(m => m.appID, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.appID, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.customerID, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.customerID, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.AccountNumber, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.AccountNumber, new { @class = "form-control" })
        </div>
    </fieldset>
    <button type="submit">Call</button>
}

APIBankingASP.NET/Views/FundsTransferByCustomerService2/getBalanceResult.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model APIBankingASP.NET.Models.FundsTransferByCustomerService2.GetBalanceResult
@using (Html.BeginForm(new { @class = "form-horizontal" }))
{
    <fieldset>
        <legend>Result</legend>
        <div class="form-group">
            @Html.LabelFor(m => m.version, new { @class = "control-label col-md-3" })
            @Html.DisplayFor(m => m.version, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.accountCurrencyCode, new { @class = "control-label col-md-3" })
            @Html.DisplayFor(m => m.accountCurrencyCode, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.accountBalanceAmount, new { @class = "control-label col-md-3" })
            @Html.DisplayFor(m => m.accountBalanceAmount, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.lowBalanceAlert, new { @class = "control-label col-md-3" })
            @Html.DisplayFor(m => m.lowBalanceAlert, new { @class = "form-control" })
        </div>
    </fieldset>

}

APIBankingASP.NET/Views/FundsTransferByCustomerService2/getStatus.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model APIBankingASP.NET.Models.FundsTransferByCustomerService2.GetStatusRequest
@using (Html.BeginForm(new { @class = "form-horizontal" }))
{
    @Html.ValidationSummary(true)

    @Html.EditorFor(m => m);

    <fieldset>
        <legend>Request</legend>
        <div class="form-group">
            @Html.LabelFor(m => m.appID, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.appID, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.customerID, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.customerID, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.requestReferenceNo, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.requestReferenceNo, new { @class = "form-control" })
        </div>
    </fieldset>
    <button type="submit">Call</button>
}

APIBankingASP.NET/Views/FundsTransferByCustomerService2/getStatusResult.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model APIBankingASP.NET.Models.FundsTransferByCustomerService2.GetStatusResult
@using (Html.BeginForm(new { @class = "form-horizontal" }))
{
    <fieldset>
        <legend>Result</legend>
        <div class="form-group">
            @Html.LabelFor(m => m.version, new { @class = "control-label col-md-3" })
            @Html.DisplayFor(m => m.version, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.transferType, new { @class = "control-label col-md-3" })
            @Html.DisplayFor(m => m.transferType, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.reqTransferType, new { @class = "control-label col-md-3" })
            @Html.DisplayFor(m => m.reqTransferType, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.transactionDate, new { @class = "control-label col-md-3" })
            @Html.DisplayFor(m => m.transactionDate, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.transferAmount, new { @class = "control-label col-md-3" })
            @Html.DisplayFor(m => m.transferAmount, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.transferCurrencyCode, new { @class = "control-label col-md-3" })
            @Html.DisplayFor(m => m.transferCurrencyCode, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.Label("statusCode", new { @class = "control-label col-md-3" })
            @Html.DisplayFor(m => m.transferStatus.statusCode, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.Label("bankReferenceNo", new { @class = "control-label col-md-3" })
            @Html.DisplayFor(m => m.transferStatus.bankReferenceNo, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.Label("reason", new { @class = "control-label col-md-3" })
            @Html.DisplayFor(m => m.transferStatus.reason, new { @class = "form-control" })
        </div>
    </fieldset>

}

APIBankingASP.NET/Views/FundsTransferByCustomerService2/transfer.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model APIBankingASP.NET.Models.FundsTransferByCustomerService2.TransferRequest
@using (Html.BeginForm(new { @class = "form-horizontal" }))
{
    @Html.EditorFor(m => m)

    <fieldset>
        <legend>Request</legend>
        <div class="form-group">
            @Html.LabelFor(m => m.uniqueRequestNo, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.uniqueRequestNo, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.customerID, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.customerID, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.debitAccountNo, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.debitAccountNo, new { @class = "form-control" })
        </div>
       
        <div class="form-group">
            @Html.LabelFor(m => m.beneficiaryAddress.address1, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.beneficiaryAddress.address1, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.beneficiaryAddress.country, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.beneficiaryAddress.country, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.beneficiaryContact.emailID, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.beneficiaryContact.emailID, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.beneficiaryContact.mobileNo, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.beneficiaryContact.mobileNo, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.beneficiaryName, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.beneficiaryName, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.beneficiaryIFSCCode, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.beneficiaryIFSCCode, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.beneficiaryMobileForMMID, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.beneficiaryMobileForMMID, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.beneficiaryMMID, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.beneficiaryMMID, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.beneficiaryAccountNo, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.beneficiaryAccountNo, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.transferAmount, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.transferAmount, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.transferCurrencyCode, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.transferCurrencyCode, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.transferType, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.transferType, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.rmtrToBeneInfo, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.rmtrToBeneInfo, new { @class = "form-control" })
        </div>
    </fieldset>

    <button type="submit">Call</button>
}

APIBankingASP.NET/Views/FundsTransferByCustomerService2/transferWithBeneCode.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model APIBankingASP.NET.Models.FundsTransferByCustomerService2.TransferRequest
@using (Html.BeginForm("transfer", "FundsTransferByCustomerService2"))
{
    @Html.EditorFor(m => m)

    <fieldset>
        <legend>Request</legend>
        <div class="form-group">
            @Html.LabelFor(m => m.uniqueRequestNo, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.uniqueRequestNo, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.customerID, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.customerID, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.debitAccountNo, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.debitAccountNo, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.purposeCode, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.purposeCode, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.beneficiaryCode, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.beneficiaryCode, new { @class = "form-control" })
        </div>
   
        <div class="form-group">
            @Html.LabelFor(m => m.transferAmount, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.transferAmount, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.transferType, new { @class = "control-label col-md-3" })
            @Html.EnumDropDownListFor(m => m.transferType, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.rmtrToBeneInfo, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.rmtrToBeneInfo, new { @class = "form-control" })
        </div>
    </fieldset>

    <button type="submit">Call</button>
}

APIBankingASP.NET/Views/FundsTransferByCustomerService2/transferWithBeneDetail.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model APIBankingASP.NET.Models.FundsTransferByCustomerService2.TransferRequest
@using (Html.BeginForm("transfer", "FundsTransferByCustomerService2"))
{
    @Html.EditorFor(m => m)

    <fieldset>
        <legend>Request</legend>
        <div class="form-group">
            @Html.LabelFor(m => m.uniqueRequestNo, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.uniqueRequestNo, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.customerID, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.customerID, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.debitAccountNo, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.debitAccountNo, new { @class = "form-control" })
        </div>
      
        <div class="form-group">
            @Html.Label("beneficiaryAddress1", new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.beneficiaryAddress.address1, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.Label("beneficiaryEmailID", new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.beneficiaryContact.emailID, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.Label("beneficiaryMobileNo", new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.beneficiaryContact.mobileNo, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.beneficiaryName, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.beneficiaryName, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.beneficiaryIFSCCode, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.beneficiaryIFSCCode, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.beneficiaryMobileForMMID, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.beneficiaryMobileForMMID, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.beneficiaryMMID, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.beneficiaryMMID, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.beneficiaryAccountNo, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.beneficiaryAccountNo, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.transferAmount, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.transferAmount, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.transferType, new { @class = "control-label col-md-3" })
            @Html.EnumDropDownListFor(m => m.transferType, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.rmtrToBeneInfo, new { @class = "control-label col-md-3" })
            @Html.EditorFor(m => m.rmtrToBeneInfo, new { @class = "form-control" })
        </div>
    </fieldset>

    <button type="submit">Call</button>
}